<?php
/*
 * export_cv.php
 * CV PDF Export - AstonCV
 * Student: Isaac Adjei (240191278)
 *
 * I generate a downloadable PDF of a single CV using mPDF.
 * I identify the CV by the id passed in the URL e.g. export_cv.php?id=1
 * Anyone can export any CV as a PDF - no login required.
 * I wrap database calls in try/catch for proper error handling.
 */

require 'db.php';
require 'vendor/autoload.php';
session_start();

// I check that an id was provided and is a valid number
if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    header('Location: index.php');
    exit;
}

$id = (int) $_GET['id'];

try {
    // I fetch the CV using a prepared statement to prevent SQL injection
    $stmt = $pdo->prepare("SELECT * FROM cvs WHERE id = ?");
    $stmt->execute([$id]);
    $cv = $stmt->fetch();
} catch (PDOException $e) {
    header('Location: index.php');
    exit;
}

// I redirect home if no CV was found with this ID
if (!$cv) {
    header('Location: index.php');
    exit;
}

// I use this helper to safely escape text for HTML output
// This prevents XSS even inside the PDF
function e($text) {
    return htmlspecialchars($text ?? '', ENT_QUOTES, 'UTF-8');
}

// I build the skills as pipe-separated text for the PDF
$skillsText = '';
if (!empty($cv['skills'])) {
    $skillsArray = array_filter(array_map('trim', explode(',', $cv['skills'])));
    $skillsText  = implode(' | ', $skillsArray);
}

// I get the first letter of the name for the avatar area
$initial = strtoupper(mb_substr(trim($cv['name']), 0, 1));

// ================================================
// I build the HTML that mPDF will convert to a PDF
// ================================================
$html = '
<html>
<head>
<style>
    body {
        font-family: Arial, sans-serif;
        font-size: 11.5px;
        color: #1a1025;
        margin: 0;
        padding: 0;
    }

    /* I use Aston University purple for the header - matches the website */
    .header {
        background-color: #5c2d82;
        color: white;
        padding: 22px 25px;
        margin-bottom: 0;
    }

    .header-inner {
        display: flex;
        align-items: center;
    }

    .header h1 {
        margin: 0 0 4px 0;
        font-size: 22px;
        font-weight: bold;
        color: white;
    }

    .header .role {
        margin: 0 0 2px 0;
        font-size: 12px;
        color: rgba(255,255,255,0.85);
        font-weight: bold;
    }

    .header .email {
        margin: 0;
        font-size: 11px;
        color: rgba(255,255,255,0.7);
    }

    /* I add a thin accent bar below the header */
    .header-bar {
        background-color: #3a1a5c;
        height: 4px;
        margin-bottom: 20px;
    }

    /* I style section headings to match the website CV detail page */
    h2 {
        font-size: 8px;
        font-weight: bold;
        color: #5c2d82;
        border-bottom: 1px solid #e2d9f3;
        padding-bottom: 3px;
        margin-top: 16px;
        margin-bottom: 7px;
        text-transform: uppercase;
        letter-spacing: 1.5px;
    }

    p {
        margin: 3px 0;
        line-height: 1.65;
        color: #3d2a55;
    }

    .skills {
        font-size: 11px;
        line-height: 1.8;
        color: #3d2a55;
    }

    /* I style the footer line at the bottom of the PDF */
    .footer {
        margin-top: 28px;
        border-top: 1px solid #e2d9f3;
        padding-top: 7px;
        font-size: 9px;
        color: #7c6f9a;
        text-align: center;
    }

    .content {
        padding: 0 25px 25px 25px;
    }

    a {
        color: #5c2d82;
    }
</style>
</head>
<body>

<!-- I use Aston purple for the header to match the website -->
<div class="header">
    <h1>' . e($cv['name']) . '</h1>
    <p class="role">' . e($cv['keyprogramming']) . ' Developer</p>
    <p class="email">' . e($cv['email']) . '</p>
</div>
<div class="header-bar"></div>

<div class="content">

    ' . (!empty($cv['profile']) ? '
    <h2>Profile Summary</h2>
    <p>' . e($cv['profile']) . '</p>
    ' : '') . '

    ' . (!empty($cv['education']) ? '
    <h2>Education</h2>
    <p>' . nl2br(e($cv['education'])) . '</p>
    ' : '') . '

    ' . (!empty($cv['work_experience']) ? '
    <h2>Work Experience</h2>
    <p>' . nl2br(e($cv['work_experience'])) . '</p>
    ' : '') . '

    ' . (!empty($skillsText) ? '
    <h2>Skills &amp; Technologies</h2>
    <p class="skills">' . e($skillsText) . '</p>
    ' : '') . '

    <h2>Key Programming Language</h2>
    <p>' . e($cv['keyprogramming']) . '</p>

    ' . (!empty($cv['URLlinks']) ? '
    <h2>Links</h2>
    <p>' . e($cv['URLlinks']) . '</p>
    ' : '') . '

    <h2>Contact</h2>
    <p>' . e($cv['email']) . '</p>

    <div class="footer">
        Generated by AstonCV &nbsp;|&nbsp; ' . date('d F Y')
    </div>

</div>
</body>
</html>
';

// ================================================
// I generate the PDF using mPDF
// ================================================

// I create a new mPDF instance with A4 page size and no top margin
$mpdf = new \Mpdf\Mpdf([
    'margin_top'    => 0,
    'margin_bottom' => 15,
    'margin_left'   => 15,
    'margin_right'  => 15,
]);

// I write the HTML into the PDF
$mpdf->WriteHTML($html);

// I create a clean filename e.g. "Samuel_Acquah_CV.pdf"
$filename = str_replace(' ', '_', $cv['name']) . '_CV.pdf';

// I send the PDF to the browser as a forced download
// 'D' = download, 'I' = open inline
$mpdf->Output($filename, 'D');
