<?php
/*
 * export_cv.php
 * CV PDF Export - AstonCV
 * Student: Isaac Adjei (240191278)
 *
 * Generates a downloadable PDF of a single CV using mPDF.
 * The CV is identified by the id passed in the URL e.g. export_cv.php?id=1
 * Anyone can export any CV as a PDF - no login required.
 */

// Load the database connection
require 'db.php';

// Load mPDF - this loads the library Composer installed
require 'vendor/autoload.php';

// Start session so we can access session data if needed
session_start();

// Check that an id was provided in the URL
if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    header('Location: index.php');
    exit;
}

$id = (int)$_GET['id'];

// Fetch the CV from the database using a prepared statement
// This prevents SQL injection
$stmt = $pdo->prepare("SELECT * FROM cvs WHERE id = ?");
$stmt->execute([$id]);
$cv = $stmt->fetch();

// If no CV found with that ID, go back to homepage
if (!$cv) {
    header('Location: index.php');
    exit;
}

// ================================================
// BUILD THE HTML CONTENT FOR THE PDF
// ================================================
// mPDF converts HTML into a PDF, so we write the
// CV layout as HTML and mPDF handles the rest.

// Helper function - safely escapes text for HTML output
// This prevents XSS even inside the PDF
function e($text) {
    return htmlspecialchars($text ?? '', ENT_QUOTES, 'UTF-8');
}

// Build skills as comma-separated text for the PDF
$skillsText = '';
if (!empty($cv['skills'])) {
    $skillsArray = array_map('trim', explode(',', $cv['skills']));
    $skillsText = implode(' | ', array_filter($skillsArray));
}

// Build the HTML that mPDF will convert into a PDF
$html = '
<html>
<head>
<style>
    body {
        font-family: Arial, sans-serif;
        font-size: 12px;
        color: #222222;
        margin: 0;
        padding: 0;
    }

    /* Top header bar with name */
    .header {
        background-color: #003B6F;
        color: white;
        padding: 20px 25px;
        margin-bottom: 20px;
    }

    .header h1 {
        margin: 0 0 5px 0;
        font-size: 24px;
        font-weight: bold;
    }

    .header p {
        margin: 0;
        font-size: 13px;
        color: #cce0ff;
    }

    /* Section headings */
    h2 {
        font-size: 13px;
        font-weight: bold;
        color: #003B6F;
        border-bottom: 2px solid #003B6F;
        padding-bottom: 4px;
        margin-top: 18px;
        margin-bottom: 8px;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    /* General paragraph text */
    p {
        margin: 4px 0;
        line-height: 1.6;
    }

    /* Info row e.g. Email: xxx */
    .info-row {
        margin-bottom: 5px;
    }

    .info-row strong {
        color: #003B6F;
    }

    /* Skills displayed inline */
    .skills {
        font-size: 12px;
        line-height: 1.8;
        color: #333;
    }

    /* Footer at the bottom of the PDF */
    .footer {
        margin-top: 30px;
        border-top: 1px solid #cccccc;
        padding-top: 8px;
        font-size: 10px;
        color: #888888;
        text-align: center;
    }

    /* Content padding */
    .content {
        padding: 0 25px 25px 25px;
    }
</style>
</head>
<body>

<!-- Header with name and key language -->
<div class="header">
    <h1>' . e($cv['name']) . '</h1>
    <p>' . e($cv['keyprogramming']) . ' Developer &nbsp;|&nbsp; ' . e($cv['email']) . '</p>
</div>

<div class="content">

    <!-- Contact section -->
    <h2>Contact</h2>
    <p class="info-row"><strong>Email:</strong> ' . e($cv['email']) . '</p>

    <!-- Profile section -->
    ' . (!empty($cv['profile']) ? '
    <h2>Profile</h2>
    <p>' . e($cv['profile']) . '</p>
    ' : '') . '

    <!-- Education section -->
    ' . (!empty($cv['education']) ? '
    <h2>Education</h2>
    <p>' . e($cv['education']) . '</p>
    ' : '') . '

    <!-- Work experience section -->
    ' . (!empty($cv['work_experience']) ? '
    <h2>Work Experience</h2>
    <p>' . nl2br(e($cv['work_experience'])) . '</p>
    ' : '') . '

    <!-- Skills section -->
    ' . (!empty($skillsText) ? '
    <h2>Skills &amp; Technologies</h2>
    <p class="skills">' . e($skillsText) . '</p>
    ' : '') . '

    <!-- Key programming language -->
    <h2>Key Programming Language</h2>
    <p>' . e($cv['keyprogramming']) . '</p>

    <!-- Links section -->
    ' . (!empty($cv['URLlinks']) ? '
    <h2>Links</h2>
    <p>' . e($cv['URLlinks']) . '</p>
    ' : '') . '

    <!-- Footer -->
    <div class="footer">
        Generated by AstonCV &nbsp;|&nbsp; ' . date('d F Y') . '
    </div>

</div>
</body>
</html>
';

// ================================================
// GENERATE THE PDF USING mPDF
// ================================================

// Create a new mPDF instance with A4 page size
$mpdf = new \Mpdf\Mpdf([
    'margin_top'    => 0,    // No top margin - our header handles spacing
    'margin_bottom' => 15,
    'margin_left'   => 15,
    'margin_right'  => 15,
]);

// Write our HTML into the PDF
$mpdf->WriteHTML($html);

// Set the filename for the download
// e.g. "Samuel_Acquah_CV.pdf"
$filename = str_replace(' ', '_', $cv['name']) . '_CV.pdf';

// Send the PDF to the browser as a download
// 'D' means force download, 'I' would open inline in browser
$mpdf->Output($filename, 'D');
?>